name: hydoxX

on:
  schedule:
    - cron: "0 23 * * *"   # 06:00 WIB setiap hari
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install --with-deps chromium

      - name: Create Google Key File
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_KEY }}' > inaproc2026key.json

      - name: Run Script
        run: node TARIKMANUALSIRUP.mjs
